services:
  app:
    image: minhpq331/news-crawler:latest
    ports:
      - 127.0.0.1:3000:3000
    restart: always
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=news_crawler
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=news_crawler
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: