services:
  app:
    build: .
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    working_dir: /app
    command: npm run dev
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=news_crawler
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=news_crawler
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
